name: Deployment
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: echo "Building..."
      - name: Deploy
        run: echo "Deploying"
